### PR TITLE
Simple API Test, bump php dependencies

### PR DESCRIPTION
**Pull request by jotoeri**
Initially i wrote this test in #1126, now splitting again for easier review.

- Adding simple API-Querying "Tests". They are by far not complete (in the sense of testing every possibility) and unfortunately not respected by the coverage, but they at least query each API-Request in full depth once, so better than nothing...^^
- In combination with these tests -> dropping php7.2 to use guzzle, thus also enabling to update to phpunit 9

### CODE REVIEW

**Comment by jotoeri** [comment]
Waiting for the big rebase once #1159 is merged.

**Comment by skjnldsv** [comment]
I created standards tests for phpunit in our github repo if you want :wink: 
https://github.com/nextcloud/forms/actions/new?category=owner

image

**Comment by jotoeri** [comment]
!! This one is based on #1087 and #1126, so the last one to merge then... :wink: !!

- [ ] Also reinclude composer.lock again (need my other pc :wink: )

**Pull request merged**
