### PR TITLE
[stable4] feat: Refactor form sync to run as a background job with retry

### PR DESCRIPTION
**Pull request by Koc**
This is backport of #2408 into `stable4`

### CODE REVIEW

**Comment by Koc** [comment]
I've tested success flow manually and it LGTM. :white_check_mark: 

Scenario:
1. created a form with short text question
2. submit 2 answers
3. link form with spreadsheet
4. submit one more answer
5. manually execute job using `./occ background-job:execute <job-id> --force-execute`

**Comment by Koc** [comment]
@Chartman123 ah, added

**Review by Chartman123 — APPROVED** [review]

**Comment by Koc** [comment]
I hope nobody against of merging it:
- pipeline green
- code review comments fixed
- manual tests passed

**Comment by toad** [comment]
@Koc @Chartman123 This is still broken at least for existing shares post upgrading to 4.3.4, because it does not correctly handle the upgrade. 

We get this error:
"Undefined array key \"attempt\" at /var/www/html/custom_apps/forms/lib/BackgroundJob/SyncSubmissionsWithLinkedFileJob.php#62"

We have patched it locally by changing SyncSubmissionsWithLinkedFileJob.php line 62 to:
`$attempt = isset($argument['attempt']) ? ($argument['attempt'] ?: 1) : 1;`

It might be a php version issue though?

**Comment by Koc** [comment]
@toad strange, I've tested it locally before merge. It seems like

```
$attempt = $argument['attempt'] ?: 1;
```

should be replaced with
```
$attempt = $argument['attempt'] ?? 1;
```

can you open PR to fix that?

**Pull request merged**
