### PR TITLE
Close navigation on mobile on new form

### PR DESCRIPTION
**Pull request by jotoeri**
- [x] On mobile, the navigation doesn’t close when you click on a form or create new

### CODE REVIEW

**Comment by jotoeri** [comment]
Ah -  and edit: Ammended a very small fix, to center the emptyContent-Description-Text on mobile.

**Comment by jotoeri** [comment]
Oups, seems like i read just half of the text.^^

**Comment by jotoeri** [comment]
Still doesn't close on Click on Answers.

@skjnldsv :
- Feels like the ActionRouter does not properly emit the @click event. Can you have a look onto this?
- Maybe the whole process 'On mobile, close navigation on click' could be a property of ActionElements? Indeed, it's very specific, but might be very commonly useful...?

**Comment by jancborchardt** [comment]
> * Maybe the whole process 'On mobile, close navigation on click' could be a property of ActionElements? Indeed, it's very specific, but might be very commonly useful...?

Might be good – if it’s possible to set per action. For example the navigation should be closed when clicking "Responses", but it should stay open when clicking "Copy share link" and "Delete form".

**Comment by jotoeri** [comment]
> Feels like the ActionRouter does not properly emit the @click event. Can you have a look onto this?

https://github.com/nextcloud/nextcloud-vue/pull/1097

**Comment by jancborchardt** [comment]
> nextcloud/nextcloud-vue#1097

That one is now merged :tada:

**Comment by jotoeri** [comment]
Still needs a release, but yes 👍 :)

**Pull request merged**
