### PR TITLE
Rename Radio buttons

### PR DESCRIPTION
**Pull request by jotoeri**
As of #1190 to hopefully get finally rid of that issue for Forms v3.

### CODE REVIEW

**Review by Chartman123 — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Comment by jotoeri** [comment]
:tada:

**Comment by Jerome-Herbinet** [comment]
Will this changed wording be added to Transiflex in order to let me translate it ?
The current "Multiple choice" wording can't be found in Transiflex (and can't be changed in French)
See : https://www.transifex.com/nextcloud/nextcloud/translate/#fr/forms?q=text%3A'Multiple+choice'

**Comment by Chartman123** [comment]
Yes, and also already translated: https://github.com/nextcloud/forms/blob/abc75634984d15ef55afc0dee43bf33afe43c1c2/l10n/fr.json#L120-L121

**Comment by Jerome-Herbinet** [comment]
> Yes, and also already translated:
> 
> https://github.com/nextcloud/forms/blob/abc75634984d15ef55afc0dee43bf33afe43c1c2/l10n/fr.json#L120-L121

Awesome, thanks !

**Pull request merged**
