### PR TITLE
Add Submit button and alignments on form creation

### PR DESCRIPTION
**Pull request by jotoeri**
Heyhey,

according to the review issue i now added a button to add options on form creation, and aligned the form-creation elements.
I'm not sure if this is now, what you would call a good style. Do you have any Coding-Styleguide or so, i could have a look into?

Greets,
Jonas

PS: As i said - i'm not that experienced yet, so please feel free to tell me, what shit i'm doing here. ;)

grafik

### CODE REVIEW

**Comment by jancborchardt** [comment]
@jotoeri do you have a link to the issue this fixes, or a before/after screenshot for context? :)

**Comment by jotoeri** [comment]
It is part of the Review-Issue #34, tackling the three points of 

>  **Form creation**
> - No way to submit/confirm answer with mouse
> - Misalignment of answers
> - Too many delete buttons visible at the same time


Old Version was:
old


New one is:
new

- Recyclebins are visible on hover
- The sidebar only scales down to the smaller width on long question texts as the lorem ipsum. Normally it has the same width as in old picture. This is a feature that was already existing.
- Maybe it is not perfect yet if you only input short questions, but otherwise it is hard to align the Option-Inputs for even long and short question-texts...

**Comment by jancborchardt** [comment]
Looks good, much better! :)

> * Recyclebins are visible on hover

Here make sure that they are also accessible via keyboard-only when people go through the entries with the Tab key. :)

**Comment by jotoeri** [comment]
Took me quite a while, but now they are also well usable on keyboard... :)

**Comment by marcelklehr** [comment]
I tend to avoid on-hover solutions, because they're not very accessible on mobile.

**Comment by jotoeri** [comment]
Well - i tested on two Smartphones and my tablet, the hover shouldn't be a problem. Just tapping onto the Item, the bin shows up. Otherwise you would have to show all delete-icons again.

Anyways i recognized, the view on mobile devices was not usable until now. I corrected that, so it would be usable. For now it would work, even that it might be necessary to have a look onto the design again after including the sidebar.

**Comment by jotoeri** [comment]
Hm, anybody else any opinion?
Is it worth to rebase and care for or should i close the PR, as these changes are not wanted? Some request for changes?
@jancborchardt @skjnldsv

**Comment by skjnldsv** [comment]
Hey @jotoeri 
Sorry about this! :)

So there is a lot of restructuring that is happening in the forms app.
Unfortunately, your pr conflicts a lot with what will happen.

I would suggest we wait until i'm done with the cleaning, and then we will be able to properly work on separate areas of forms, what do you think? :)

**Comment by jotoeri** [comment]
Ok, tank you for the information. :)

I'm currently also working on the Database-Thing #206. Sounds like i better stop this work until you are done? ([Branch alter_Db](https://github.com/jotoeri/forms/tree/alter_Db/develop) Branch is a bit dirty until now.... )

**Comment by skjnldsv** [comment]
I do not touch much in the backend, so we should be safe here :)

**Comment by jotoeri** [comment]
Ok :)

**Pull request closed without merging**
