### PR TITLE
Add technical identifiers for questions

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #1040

### Summary
Technical identifiers allow to map form questions to custom data.
On the frontend those identifiers are implemented as `name` props on the form elements.

### Screenshots
Name input:
name input on question actions menu

### Other notes
The name attribute for technical identifier should be mapped to all options so a `fieldset` is introduced around radio / checkbox buttons.
Added required aria label for `fieldset` (labeled by the question title).

### CODE REVIEW

**Review by Chartman123 — APPROVED** [review]
Could you please put the two commits in one before merging? I don't think that it's really needed to have two commits here :) Rest seems fine.

**Comment by susnux** [comment]
@Chartman123 Shure, done. The second commit was just for review purpose to see why I changed it :)

**Comment by Chartman123** [comment]
@susnux Please also add the new prop to the API docs :)

**Comment by susnux** [comment]
> Please also add the new prop to the API docs :)

Done :heavy_check_mark:

**Pull request merged**
