### PR TITLE
Add Question Description

### PR DESCRIPTION
**Pull request by jotoeri**
Adding a simple description to questions. Could somewhen be formattable, but for now implements #321 

One thing, that i personally dont like is that the scrollHeight of the textarea seems to have a minimum, that we cannot set. Thus, for short Descriptions, the textarea is relatively large and the content around jumps a bit when enabling/disabling edit-mode. So if sbdy has a good idea to solve that, please tell me, apart from that i think we can go for now with this...

grafik

<details>
<summary>Initial image</summary>

grafik

</details>

### CODE REVIEW

**Comment by jotoeri** [comment]
Note to self:
- [ ] Move maxStringLengths to Constants::
https://github.com/nextcloud/forms/blob/4b23e63a67e720d06dfcd17466f7ae2266bdb682/lib/Controller/PageController.php#L96

**Comment by Chartman123** [comment]
> and the content around jumps a bit

@jotoeri I wouldn't mind. For existing questions without description the lower elements also jump around when you enter the edit mode for that question later

**Comment by Chartman123** [comment]
I was able to fix it for Chrome and at least enhance it for Firefox by adding rows="1" to the textarea.

**Review by Chartman123 — APPROVED** [review]
If you autosquash my fixup commit, I think that we're good to go here. Perhaps you can find an even better solution for firefox if you dive deeper into the web 🙂

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Very cool enhancement! :) Just 1 detail: Instead of using italic which can be difficult to read for people, we can use `color: var(--color-text-maxcontrast)`.

**Review by skjnldsv — APPROVED** [review]
Looks good aside from Jan's comment :)

**Comment by jotoeri** [comment]
Changed to color maxcontrast. Now i got some other issue, that the color does not apply anymore as long as i hold the mouse button. @skjnldsv @jancborchardt Any idea, which class/property could kick in here? 🤔 

Animation

**Pull request merged**
