### PR TITLE
Bump php-dependencies

### LINKED ISSUE #1145: thephpleague/csv does not support PHP 8
It seems that the forms app requires `"league/csv": "^9.5"` (in `composer.json`), while >= 9.6.2 is [required](https://github.com/thephpleague/csv#system-requirements) for PHP 8.0 support and >= 9.7.3 for PHP 8.1 support.

This is probably the reason I'm getting this error:

```
Type of League\\Csv\\EncloseField::$filtername must be string (as in class php_user_filter) at /var/lib/nextcloud/apps/forms/vendor/league/csv/src/EncloseField.php
```

Could we bump the dependency to 9.7.3?

### PR DESCRIPTION
**Pull request by jotoeri**
Taking this out of #1149 to get the php8 tests running. Also closes #1145

### CODE REVIEW

**Comment by jotoeri** [comment]
All green now! 🎉
And even coverage is happy for nothing... 😆

**Comment by jotoeri** [comment]
----------- STOP ---------
Argh. Migration to v3 does not run with this PR currently.
(Since when can't i request changes on my own PR...?) :(

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — DISMISSED** [review]
blocked

**Comment by jotoeri** [comment]
So - got it working. With this, the 
The problem is different symfony versions on server and php-cs-fixer. Similar to https://github.com/nextcloud/twofactor_webauthn/pull/132 i scoped the cs-fixer dependency now. The only drawback currently is, that we have to run composer install twice on a new machine to make the cs-fixer work (see also https://github.com/bamarni/composer-bin-plugin/issues/72).

**Pull request merged**
