### PR TITLE
Ignore Compile-Cache

### PR DESCRIPTION
**Pull request by jotoeri**
Can we include this one? I'm not sure if you see this too, but i run quite often into the problem to commit the compile-cache... :/

### CODE REVIEW

**Comment by skjnldsv** [comment]
Where is it coming from?

**Comment by jotoeri** [comment]
Make build-js produces the directory...

**Comment by skjnldsv** [comment]
Do you have a proper npm setup on your local user?
I guess you should setup npm to use a local folder?
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by jotoeri** [comment]
Hm, i followed the steps on you link, but still get the folder...
I'm working on a WSL-Machine as root, to be honest (Some poeple would like to kill me for this? :D). So i don't know, if there are any differences due to this... But doesn't matter. The gitignore suffices for now and a compile-cache shouldn't be a bad thing in general, i think... ;)

**Comment by skjnldsv** [comment]
Ah, no idea for your setup then :)

**Pull request merged**
