### PR TITLE
Replace app icon with Material Symbols version

### PR DESCRIPTION
**Pull request by AndyScherzinger**
in the quest of (slightly) harmonizing the app icons in the ecosystem I replaced the app icon with the Material Symbols version.
SVGs are optimized for file size.

### CODE REVIEW

**Comment by Chartman123** [comment]
@AndyScherzinger Thanks :) should we also replace the SVG part in FormsIcon.vue?

**Comment by AndyScherzinger** [comment]
@Chartman123 yes, makes sense I would say 👍

**Review by Chartman123 — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
🎉 THANKS for merging and for taking care of the vue change 🙏

**Comment by Chartman123** [comment]
You're welcome, I have to thank you for bringing it up in the first place! 👍🏻

**Pull request merged**
