### PR TITLE
Fix question icons broken in dark theme

### PR DESCRIPTION
**Pull request by skjnldsv**
Capture d’écran_2020-04-29_12-24-49

### CODE REVIEW

**Comment by skjnldsv** [comment]
> Don't know how it looked before, but looks good. ;)

Only the two first were inverted
image

**Comment by jancborchardt** [comment]
Just noticed – the primary button icon (and text) should be white in the dark theme as well, as otherwise it's not enough contrast.

**Comment by skjnldsv** [comment]
@jancborchardt can you add that to the list so it's not lost? :)

**Comment by jancborchardt** [comment]
> @jancborchardt can you add that to the list so it's not lost? :)

Isn't it an issue for the Vue repository?

**Comment by skjnldsv** [comment]
No, we're enfocring the icon with ours :)
It won't be an issue anymore with the icon library though ;) (since we'd be able to use css `color`)

**Pull request merged**
