### PR TITLE
Include version on feature-request template

### PR DESCRIPTION
**Pull request by jotoeri**
For easier processing of requests, especially if we think they are done already.

### CODE REVIEW

**Comment by jancborchardt** [comment]
I'd say put the current server version in (19.0.?) and also the anticipated new Notes release (2.0.0), that way people see what they ideally should be using. :)

**Comment by jotoeri** [comment]
Thats good idea, yes :+1:
Would you mind to have a look onto both templates again (feature-request & bug-report) from side of UX? 
How do we get users to really use the templates and provide us the information, we need? It happens (quite often), that users don't use esp. the bug-template...

**Comment by jancborchardt** [comment]
> Would you mind to have a look onto both templates again (feature-request & bug-report) from side of UX?
> How do we get users to really use the templates and provide us the information, we need? It happens (quite often), that users don't use esp. the bug-template...

The biggest issue usually is that the template is too long, but that’s not the case here. Might just be a matter of if anything is missing to ask people to use the template (and not individually asking "what’s the version" etc.).

**Comment by jotoeri** [comment]
Hm, ok... So then this one should be good to go now...?

**Comment by jotoeri** [comment]
Ah - or how do you think about shortening the first text as in the fixup? I think i personally would also wonder, if i first get told 'how to use the website'.

**Comment by jancborchardt** [comment]
> Ah - or how do you think about shortening the first text as in the fixup? I think i personally would also wonder, if i first get told 'how to use the website'.

Yeees! So much better, and it's not so confusing. I was also always wondering if that is something to remove, but it's there for peopel _reading_ the issue. :D

**Pull request merged**
