### PR TITLE
Make possible hide fields from header

### PR DESCRIPTION
**Pull request by vitormattos**
## Motivation

Make possible use a form embedded in a site as contact form by example. A contact form sometimes haven't a description.

## Before

Screenshot_20230825_130148

## After
Screenshot_20230825_130158

**How I implemented?**
I searched by `show?(expiration)` to look all places with this property and added the changes

### CODE REVIEW

**Comment by Chartman123** [comment]
Hi @vitormattos

thank you for your contribution. However, I don't get your point as the description will only be shown if it's set. Why don't you just leave it empty when you don't want to show it?

**Comment by vitormattos** [comment]
Hi @Chartman123,
Maybe the admin will want to put a description to herself to identify the purpose of form or any other reason, and don't want to display the description to users.

**Comment by vitormattos** [comment]
This PR can complement the use cases generated by #1353

**Comment by vitormattos** [comment]
I did a more push to make possible completely hide the header.

**Comment by vitormattos** [comment]
@jotoeri maybe we can maintain only the option to completely hide the header.

> I'd rather try to keep the UI simple instead of configuring every tiny bit.
> 
> > description to herself to identify the purpose of form or any other reason
> 
> That is more a mis-usage of the intended description field. So you'd basically with this only introduce an option to mis-use a functionality. With the drawback of a more complex UI. That's not the intention of the app.

**Comment by jotoeri** [comment]
> @jotoeri maybe we can maintain only the option to completely hide the header.

Would be at least less disturbing, yes.
->  But still it's an option for a specific use-case, that you might have for embedding. 90% of the users just see a very strange option to create a head-less form. Why not just hiding the header via css on your specific embedding?

**Comment by vitormattos** [comment]
Hiding only by CSS will make necessary touch the code creating a new app or implementing the CSS in another place. This  could have problems in a future change of id or class used to generate the CSS selector making very hardy to maintain the CSS customization.

Other point is that isn't all user that know how to use CSS to hide elements.

Exists an app to inject CSS without touching the code creating a new app to only hide the header of a form, but  this also is a overhead because when more app we have, more slow our Nextcloud instance will be because is more apps that need to be initialized.

**Comment by Chartman123** [comment]
@jotoeri @vitormattos

As this is intended mainly towards embedded forms, what about moving the setting to the menu of an embedding enabled link?

And I'd also like to have only one setting for the whole header if we agree on having it added :)

**Comment by vitormattos** [comment]
Hi @jotoeri & @Chartman123 ,

After our messages yesterday, I changed my PR reverting the implementation of toggle to title and description and kept only the toggle of header.

Could look if now is OK?

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Design-wise I would reject this as it goes against one of our design guidelines which is to not offer settings for every little thing – as was mentioned already. :)

**Comment by Chartman123** [comment]
Ok, so I'll close this. And as we already pointed out theres a workaround using custom css to hide the information when a form is embedded into another site.

**Pull request closed without merging**
