### PR TITLE
Delete empty options from Db

### PR DESCRIPTION
**Pull request by jotoeri**
> - [x] When emptying an answer and leaving the edit mode, it remove the empty one (on purpose) but not removed from the database

### CODE REVIEW

**Comment by jancborchardt** [comment]
(Can’t review here as it’s mostly code review, cc'ing other Vue people.)

**Comment by jotoeri** [comment]
Well we need to delete them somehow. If you don't do here, you will have an inconsitency between Db and UI, which falls back, the moment you reload the form.
The case, that this gets triggered on very many answers within one moment is very unlikely. If people want to delete the answers, they will trigger the delete (also from Db) anyways by delete button or backspace-key (not just clearing every answer-text manually and leaving the field there as empty answer). The case that there are empty answers left, that get deleted within one moment won't be used on really many answers, i think.

**Comment by jancborchardt** [comment]
Can you recheck @skjnldsv? :)

**Comment by skjnldsv** [comment]
Ah, I missed the original point, sorry.
I was thinking about deleted options that we keep so that submitted answers still have the original option shown. My bad!

I'm not fond of doing a function call within a filter.
But it's ok :)

**Comment by jotoeri** [comment]
Second review necessary? Or just go ahead?

**Comment by skjnldsv** [comment]
Let's go

**Pull request merged**
