### PR TITLE
Revert topbar changes

### PR DESCRIPTION
**Pull request by skjnldsv**
Revert changes
Like the Talk standard.

Capture d’écran_2020-05-06_13-03-33

### CODE REVIEW

**Comment by jotoeri** [comment]
- Well, if we change back here, then let's do everything alright, to adapt all the button-heights to a common height.
- The `&:not(.button-small)` change in top-bar was done by Jan as his design-review. You're sure you want to revert that?
- Will we never use a second large button on the top-bar? I tried that already once before on dev and the top-bar was not very handy with this not-first.

**Comment by skjnldsv** [comment]
> * Will we never use a second large button on the top-bar? I tried that already once before on dev and the top-bar was not very handy with this not-first.

a second vue Actions you mean?

**Comment by skjnldsv** [comment]
> * Well, if we change back here, then let's do everything alright, to adapt all the button-heights to a common height.

Design specs from talk are like those, regular buttons with text are server styling, icon-only button 44x44.
Like it is with this pr

**Comment by skjnldsv** [comment]
> * The `&:not(.button-small)` change in top-bar was done by Jan as his design-review. You're sure you want to revert that?

I'm sure, but Jan might not, let's see with him.

**Pull request merged**
