### PR TITLE
chore: Use prettier for stylistic rules

### PR DESCRIPTION
**Pull request by Chartman123**

### CODE REVIEW

**Comment by Chartman123** [comment]
@susnux I followed the setup guide in the prettier-config repo, however, there are some errors ... Could you please have a look at it and adjust the documentation if there's something missing?

**Comment by susnux** [comment]
> @susnux I followed the setup guide in the prettier-config repo, however, there are some errors ... Could you please have a look at it and adjust the documentation if there's something missing?

You need to install the eslint configuration:

npm install --save-dev eslint-config-prettier

**Comment by Chartman123** [comment]
Thanks, that helped :)

**Review by susnux — APPROVED** [review]
Makes sense for me, but lets only do this if you agree with the formatting @Chartman123

**Comment by Chartman123** [comment]
> Makes sense for me, but lets only do this if you agree with the formatting @Chartman123

I'll have a closer look at the changes before merging :)

**Comment by Chartman123** [comment]
@susnux should we wait with merging this PR until @Koc has finished the file question PR? Otherwise there will be lots of merge conflicts I assume...

**Pull request merged**
