### PR TITLE
Unnecessary $questions assignment removed

### PR DESCRIPTION
**Pull request by ordaolmayanadam**
$questions assignment is not used in the function so removed

### CODE REVIEW

**Comment by jancborchardt** [comment]
The build fails with PHP 7.1, but I assume that’s a separate issue? cc @skjnldsv

**Comment by jancborchardt** [comment]
Can you check this @skjnldsv? :)

**Comment by skjnldsv** [comment]
> Can you check this @skjnldsv? :)

I have no clue ^^

**Comment by marcelklehr** [comment]
> `CORE_BRANCH=master`

Does master still support php v7.1?

**Comment by skjnldsv** [comment]
> Does master still support php v7.1?

guess not, we also support 7.4

**Comment by jancborchardt** [comment]
> > Can you check this @skjnldsv? :)
> 
> I have no clue ^^

Do you know who has a clue? :) @rullzer maybe?

**Comment by rullzer** [comment]
Rebase on master and all should be good

**Pull request merged**
