### PR TITLE
Create API Reference Documentation

### PR DESCRIPTION
**Pull request by Brennakm**
Just creating a file for API documentation.

### CODE REVIEW

**Comment by jotoeri** [comment]
@Brennakm i'm not sure about, maybe i interpret wrong, but it looks a bit to me like you wanted to create the file here on the Repository by adding it here on github and are now waiting for the file to get created? ;)
(I just ask to not get stuck on this because of misinterpretations... ;))

**Comment by Brennakm** [comment]
@jotoeri Hi! Yes, I was trying to create a file for the API documentation (not complete yet, just a draft). But I got an error saying "PHPUnit / php7.4-mysql-master (pull_request)" failed. I'm not super familiar with GitHub so I've been trying to see if I have everything properly installed. Let me know if I am doing something incorrectly, I don't want to disrupt the team's process :)

**Comment by skjnldsv** [comment]
> Yes, I was trying to create a file for the API documentation (not complete yet, just a draft). But I got an error saying "PHPUnit / php7.4-mysql-master (pull_request)"

You can ignore this, this is a timeout :)
You can keep pushing to this branch with your changes :+1:

**Comment by jotoeri** [comment]
Hehe, all good. 👍 
So that error, that you see here is nothing, that you did wrong. That just happens from time to time, that these tests don't pass due to an internal error. When running again, it will pass without problem. So nothing you did wrong.

In General, the typical workflow with Git is to develop a feature on a separate 'branch', to get it finished and polished and then it gets merged into the master-branch. While creating the file, Github created such a branch for you on your account and named it 'patch-1'. This pull-request is then the step to get it into the master-branch. As it is not finished yet, nobody of us merged this Pull-Request, John just marked it as 'still in development'.

So two things:
- On your own account here on Github, there is now a repository 'forms', that is just a copy of the original repository. In the Code-View there, you can on the top-left choose the 'patch-1'-branch and you will see, that your file exists there. There you can edit your file already and everything that you commit there will appear here on the pull-request, as the PR is then the way to get the work into this original repository.

- Apart from that, I can recommend you the app [Git-It-Electron](https://github.com/jlord/git-it-electron), that is a small lerning-tool, to get and understand the basic idea of Git and Github. If you got that, you'll see it is quite easy to understand, what happens here. The app itself is quite easy to complete and can be done within a few hours. I also learned about Git with this tool last year.
--> Just to say directly: The first challenge of the app is a bit outdated, you will need to install Git directly from [git-scm.com](https://git-scm.com) instead of installing the Github-Desktop app.
--> A few things, such as signing commits, rebasing, fixups are not covered, but you will learn about those afterwards here. But that won't be a problem, once you got the basics...

**Comment by michimau** [comment]
can it be done better?
https://gist.github.com/michimau/6dc23c8ad5604f46814426de7c0b170c

**Comment by jotoeri** [comment]
Hey @Brennakm,

i included the docs now on a separate PR as i was working on the api anyways. So i close this PR for now. If you're still interested in contributing to forms, just let us know! 😉 

Greets,
Jonas

**Pull request closed without merging**
