### PR TITLE
Add Date & Datetime Component

### PR DESCRIPTION
**Pull request by jotoeri**
Now continuing on the previous Date-PR #604
- Based onto #671 (& includes its main-aspect), as this allows moment to format the date here
- Merged the two Component-Files into one, as there was one line of code difference.
- Fixed the review-stuff from the other PR
- Now stores the selected date as String, just as the user selected it.

@jancborchardt Could you have a look onto design?

@simmstein Unfortunately i can't 'officially' request your review here, but would still be happy to get your review/opinion/test. :)

### CODE REVIEW

**Comment by simmstein** [comment]
Perfect!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Please rebase & squash :)

**Comment by jotoeri** [comment]
@jancborchardt Anything from your side?

**Comment by u451f** [comment]
Super cool that this feature was implemented! Thanks! 
I don't understand in which version of NC Forms this feature is available, can you help me understand? Sorry if this is obvious and I missed it.

**Comment by u451f** [comment]
Replying to myself: https://github.com/nextcloud/forms/releases/tag/v2.1.0 <3

**Pull request merged**
