### PR TITLE
fix: Parse momentFormat and storageFormat

### LINKED ISSUE #2091: Date fields don't show their previously entered values upon reloading
Steps to reproduce: 
1. Enter a date into a date field
2. Leave view and go back to view / reload window
3. See missing date

The date gets stored correctly in the local storage but isn't loaded back. Might be related to #1969

### PR DESCRIPTION
**Pull request by Chartman123**
This fixes #2091 by parsing the momentFormat `L` or the storageFormat `YYYY-MM-DD`.

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
We should have regression tests for things like this ;)

**Comment by Chartman123** [comment]
> We should have regression tests for things like this ;)

Can this be achieved with E2E tests?

**Pull request merged**
