### PR TITLE
Include more sharing links

### PR DESCRIPTION
**Pull request by jotoeri**
Fixes
> - [x] Not clear how to get share link, needs to be in sidebar next to radio option too, and ideally in responses view too when empty

- Included a link on EmptyContent in results
- Included a link in Sidebar
- Changed the Clipboard-package to fix closing of Actions-Menu, when copying link (now remains open, showing the nice green checkmark). [Found that package here](https://vuejsexamples.com/a-clipboard-library-with-vue-js/)

grafik
grafik
grafik

### CODE REVIEW

**Comment by skjnldsv** [comment]
Ah, please use the Actions menu on the sidebar then :)
It's dedicated for those uses exactly :wink: 
https://nextcloud-vue-components.netlify.app/#/Components/App%20containers?id=appsidebar-1

```
	<AppSidebar>
	...
		<template #secondary-actions>
			<ActionButton>
				{{ t('forms', 'Copy to clipboard') }}
			</ActionButton>
		</template>
	</AppSidebar>
```

**Comment by jancborchardt** [comment]
> 

The "Copy share link" button should only show when the "Share link" radio button is selected, as otherwise it is not active, no? (And in that case it should also show next to that radio option, in the same line.

(Sidenote: German translation could be improved if you are on Transifex, shouldn’t say "Öffentlich" as it’s not public – maybe something like "Link teilen".)

**Comment by jotoeri** [comment]
As for now, users don't get a message, if the form is shared to them. So the link is still necessary on all sharing-options.
But yes, for when notifications are running, it will be good to do sharing like this.

**Comment by jotoeri** [comment]
This is when i use the secondary-actions-slot.
@jancborchardt Different design works for you?

grafik

**Comment by jancborchardt** [comment]
Hmm, since this _should_ be the main way to get the share link, I’m not sure about it. Let’s get it in for now since the pull request improves it a lot, but it being icon-only and separated from the actual "Sharing" settings below, there will be issues.

**Comment by jotoeri** [comment]
Well i didn't finish the work & commit yet. This is why i ask.
Alternative would be to merge as it was [above](https://user-images.githubusercontent.com/47433654/81272708-1efd7f80-904e-11ea-8267-061ef54a89ea.png)

**Comment by skjnldsv** [comment]
> Let’s get it in for now since the pull request improves it a lot, but it being icon-only and separated from the actual "Sharing" settings below, there will be issues.

I'd guess we should also think about others app, Talk is also having the copy to clipboard there?

**Comment by skjnldsv** [comment]
> This is when i use the secondary-actions-slot. (Less visible...?)
> @jancborchardt Different design works for you?
> 
> grafik

Looks good to me :)

**Comment by jotoeri** [comment]
grafik
grafik

**Pull request merged**
