### PR TITLE
fix(Question): Do not place popover within question but on body

### LINKED ISSUE #1840: Question menu overlayed by three dot menu button
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When you open the menu of a question and the menu is long enough to reach the next questions three dot menu button, this button overlays the menu.

**Expected behavior**
Menu should be above button

**Screenshots**
grafik

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28 RC1
- Forms-Version: current main

### PR DESCRIPTION
**Pull request by susnux**
Fix #1840 

Fix the placement of the popover and remove unneeded styles.

### CODE REVIEW

**Comment by susnux** [comment]
Is a backport needed for v3?

**Comment by Chartman123** [comment]
I don't know, I currently don't have a test/dev instance anymore... But I could spin one up in the next few days

**Comment by Chartman123** [comment]
> Is a backport needed for v3?

@susnux I thought about it and probably won't hurt there, so I think we should just backport it?

**Review by Chartman123 — APPROVED** [review]

**Pull request merged**
