### PR TITLE
Fixing several small things

### PR DESCRIPTION
**Pull request by jotoeri**
- Removing the last scss files
- On public.css removing css that is identically provided by server, and fixing the footer-position on public pages
- Fixing the public 'Shared by', as `VISIBILITY_PUBLIC` is deprecated since NC21
-  Dont render the topbar on public views, as it does not show anything.
- Fix Drag-Handle Position and Cursor

### CODE REVIEW

**Comment by Chartman123** [comment]
> * fixing the footer-position on public pages

grafik

For me it's still outside the visible area and I have to scroll to see it

**Comment by jotoeri** [comment]
> For me it's still outside the visible area and I have to scroll to see it. (The lighter grey area is my taskbar)

How long is your Form? Only for very short forms you shouldnt need to scroll. For longer forms, the footer is still at the End of the Form.

**Comment by Chartman123** [comment]
> > For me it's still outside the visible area and I have to scroll to see it. (The lighter grey area is my taskbar)
> 
> How long is your Form? Only for very short forms you shouldnt need to scroll. For longer forms, the footer is still at the End of the Form.

It was a form showing the NcEmptyContent because it has already been expired. So there was plenty of space for the footer 😉

**Comment by jotoeri** [comment]
Now also works with the emptycontent.^^

**Review by Chartman123 — APPROVED** [review]

**Pull request merged**
