### PR TITLE
Prevent letter debounce erasing when creating new answers

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix the letter erasing issues when creating a new nswer

### CODE REVIEW

**Comment by jotoeri** [comment]
Hm, before i mostly lost the second letter, now i loose the first letter... :D

**Comment by skjnldsv** [comment]
> Hm, before i mostly lost the second letter, now i loose the first letter... :D

I don't, works fine for me :thinking:

**Comment by skjnldsv** [comment]
I pushed something different, mind to test again?

**Comment by jancborchardt** [comment]
Thanks a lot for fixing this @skjnldsv!!! :)

**Pull request merged**
