### PR TITLE
Make 'unique' an integer

### PR DESCRIPTION
**Pull request by jotoeri**
Solves #176 #189

Greets,
Jonas

PS: Somebody able to release a V1.1.1? I think this would make the app at least usable as-is for many users again, since aboves Issues, as well as #166 would be solved...?!

### CODE REVIEW

**Comment by jotoeri** [comment]
And sorry for this number of force-pushed versions of the commit. I was just struggling with the DCO-Check.

**Comment by jotoeri** [comment]
That't true. I chose this way, as the two Anonymous-Columns are handled as integer, too.
But indeed, it would make sense to alter all three to proper boolean columns. Maybe as part of #206 ? ;)

**Comment by juliushaertl** [comment]
> But indeed, it would make sense to alter all three to proper boolean columns. Maybe as part of #206 ? ;)

Yes, if there is more to cleanup, it makes sense to do this separately and properly planned :+1:

**Comment by skjnldsv** [comment]
@jotoeri so you'll tackle the rest in a followup pr?

**Comment by jotoeri** [comment]
I'm not sure if i can do it all on my own, as its quite much to do and i'm not very experienced yet. But if a few people are working together on it, i will gladly participate or start with it.
Would be nice if some of you could give their opinion on #206 .

**Comment by rullzer** [comment]
@skjnldsv maybe setup a talk room for forms?

**Comment by skjnldsv** [comment]
https://cloud.nextcloud.com/call/im4cw68i :)

**Pull request merged**
