### PR TITLE
API v2

### PR DESCRIPTION
**Pull request by jotoeri**
This is in fact a part of #1087. Splitting this off for easier review.

- Moving the whole API to v2
- I first tried to keep API v1.1, however mapping the new sharing to the old way is way too hard for its benefit. Thus - even that not good at all - I'd drop API v1.1. To have at least some 'compatibility' for outside API users, a capabilities response should hint on which API exists on the instance. #1146
- Adapt API Documentation to changes
- Add Sharing-Part to API-Doc

### CODE REVIEW

**Comment by jotoeri** [comment]
- [ ] Revert #1162 to get proper response again

**Comment by jotoeri** [comment]
Ok - so @Chartman123 @skjnldsv This should now be a quite simple review, as it is only the first commit to check. The second commit has been done with #1148

**Comment by Chartman123** [comment]
> Ok - so @Chartman123 @skjnldsv This should now be a quite simple review, as it is only the first commit to check. The second commit has been done with #1148 

OK, I'll try to find some time to dive into this. :)

**Review by Chartman123 — APPROVED** [review]
Didn't run the code, but couldn't find any obvious problems by reviewing the code :)

**Comment by jotoeri** [comment]
I tested it quite a few times meanwhile, i think. 😉

**Pull request merged**
