### PR TITLE
add date and datetime

### PR DESCRIPTION
**Pull request by simmstein**
see #499

### CODE REVIEW

**Review by skjnldsv — DISMISSED** [review]

**Review by jotoeri — CHANGES_REQUESTED** [review]
We need to take care, how this is stored. Currently i get these results, while i selected the 16.09. on the first two points. So timezone kills here, what i really selected!
grafik

Few things still to do. I would not really like to merge this now just as quick-stuff, but then needing to care afterwards to fix all this. I think we have the time to do it properly.
- Just to have it linked here once: [Vue Docs DatetimePicker](https://nextcloud-vue-components.netlify.app/#/Components/DatetimePicker) - [Datepicker Doc](https://github.com/mengxiong10/vue2-datepicker)

**Comment by loelkes** [comment]
@skjnldsv Sorry, I can't follow. Why is this outdated? 
@simmstein Are you still working on it?

**Comment by simmstein** [comment]
I gave up because the first PR was in july and nothing happened. I wanted to help but I don't think you want it.

**Comment by skjnldsv** [comment]
Hey @simmstein 
Have you see the comments and change requests by @jotoeri ?

**Comment by jotoeri** [comment]
Hey you three :)

@loelkes What skjnldsv marked as outdated here was just his review, after i submitted my review. It was not meant the PR is outdated.
@simmstein It is of course wanted if you want to contribute, I didn't want to stop you from. I myself are a community member just doing this on my free time, not better than you or somebody else. My intention on the reviews is just that the master-branch should be a mostly stable version of the code, so if there are already obvious errors on a new code, it should be fixed before merging it. I'd even say, that this is one of the main concepts of Git, to develop on a separate branch, get reviews, fix stuff, until a feature is stable and usable and then to merge. Such, you get an application, that should nearly always be usable on master-branch.

To be honest, I have this PR on backlog, to fix the stuff I marked on my review and to reactivate it then. I just don't have much of a time currently and several other projects on the run. But if I get back to forms, that might be one of my first things to do (if nobody else did until then...).

Greets,
Jonas

**Comment by jotoeri** [comment]
Ok, so i found some time today to have a look onto. Changes are on branch `enh/add_date_time`, i just didn't manage to push to the previous branch.
@skjnldsv Two things:
- Could you please have a look onto the date-format & storing? I thought about just storing the date in filling-users' locale&timezone as string. So we have least confusion, we just store exactly what the user sees & selects. (And in case forms-creator and user use different locale/tz they will need to consent on a common format. But probably that's anyways better than if our software just does some predefined stuff.) On Sidebar you did great stuff with the date-picker, that does just not work for me 🙄 🙈 . See on the last commit, i finally tried to copy your version of locale handling, but the locale-import does not work anymore on submission.... You might have a better overview & idea there!?
- Could you maybe check, if you can change the pr-branch here? Otherwise we just open a new PR?

**Pull request closed without merging**
