### PR TITLE
chore(phpunit): Switch to phpunit workflow from organization

### PR DESCRIPTION
**Pull request by susnux**

### CODE REVIEW

**Comment by susnux** [comment]
Only integration is failing, but I do not understand:
The form that is exported is **not** anonymous, so all users should be returned by their ID / displayname.
Why did the test ever expect to return anonymous?

**Comment by Chartman123** [comment]
> Why did the test ever expect to return anonymous?

In the current PHPUnit-WF we created one user `user1`, user2 and user3 did not exist in the test environment. Might this be the cause for this?

**Comment by susnux** [comment]
Ah yes I see so it tests for user2 and user3 are deleted users...

**Comment by susnux** [comment]
Not related but maybe we then need to anonymize reponses on user-deleted events, because otherwise they would be connected to new users with the same ID

**Comment by Chartman123** [comment]
> Ah yes I see so it tests for user2 and user3 are deleted users... 

Yes, that's how I understand it

**Comment by Chartman123** [comment]
> Not related but maybe we then need to anonymize reponses on user-deleted events, because otherwise they would be connected to new users with the same ID

Good idea :) could you please create a new issue for that?

**Review by Chartman123 — APPROVED** [review]

**Pull request merged**
