### PR TITLE
Improve and unify Markdown output style

### PR DESCRIPTION
**Pull request by susnux**
Improve the output style the get a consistent styling across apps (e.g. this style is used by `text` and `collectives`.
* Add background to code (blocks)
* Add list styles
* Add block quote backgrounds (requires #1574 because otherwise you can not create block quotes (`> ...`)).

before | after
---|---
No indention, no styling | basic styling

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Niiiice! @susnux great stuff as usual! :sparkles: 

Requesting review from our Markdown/Text experts @max-nextcloud and @mejo- as well. :)

**Review by jotoeri — APPROVED** [review]
🚀

**Review by mejo- — APPROVED** [review]
Awesome, thanks @susnux. I don't have much insights into the Forms app, but screenshots and code changes look sensible and like a great improvement.

**Review by Chartman123 — APPROVED** [review]

**Pull request merged**
