### PR TITLE
Fix Popover-Reference

### LINKED ISSUE #609: delete answer menu incorrectly positioned
**Describe the bug**
made a simple form. publish. get answers. 
i want to delete one and click the icon with the 3 dots and then the popup menu with the option to delete answer is incorrectly positioned
the above happens for the 3rd answer in the list and after.
1st and 2nd answer delete menu shows in place

**To Reproduce**
1. made a simple form A. publish. get answers. 
2. log as admin, go to forms and to form A.
3. go to answers list
4. try to delete one (3rd and after)

**Expected behavior**
click the icon with the 3 dots and then the popup menu with the option to delete answer is correctly positioned

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.9
- Forms-Version: 2.0.4

**Desktop (please complete the following information):**
 - OS: win7 32bit el
 - Browser firefox 
 - Version 80.0.1 32bit

### PR DESCRIPTION
**Pull request by jotoeri**
Just the fix proposed by raimund-schluessler in https://github.com/nextcloud/nextcloud-vue/issues/1384
Thought mainly as a short-term fix here until it is solved in server or vue-components.
- Mainly for a backport-fix and a release of v2.0.5 @skjnldsv ? Might need a separate branch `stable2.0`?

Fixes #609

### CODE REVIEW

**Comment by skjnldsv** [comment]
No we keep releasing like that on master :)
Master is 2.0.4, backports are for majors usually https://github.com/nextcloud/forms/blob/3c6452fca410c5495b4bc04c71f1a5e4e60e4fcc/appinfo/info.xml#L14

**Comment by jotoeri** [comment]
> Master is 2.0.4, backports are for majors usually

Also fine by me... Just thought to keep the date-questiontype for 2.1. 👍

**Comment by skjnldsv** [comment]
> Just thought to keep the date-questiontype for 2.1.

Ah right! Nah it's fine, we can always release minors like that, people will upgrade.

**Review by skjnldsv — APPROVED** [review]

**Comment by jotoeri** [comment]
> > Just thought to keep the date-questiontype for 2.1.
> 
> Ah right! Nah it's fine, we can always release minors like that, people will upgrade.

I think we're talking on different aspects. :D 
Sure, people will update, if there is a release. No question, i agree with you.
But if we want to release this popover-fix now (which would be helpful imo to fix the current release), but 2.1 is not done yet as it is still missing many planned features, then we need a 2.0.5. But if date-questions are for 2.1., we'd now need to produce a 2.0.5 with this popover-fix but without date-questions...

**Pull request merged**
