### PR TITLE
Use cancelable request

### PR DESCRIPTION
**Pull request by jotoeri**
Including the planned cancelable request on fetchFullForm.

Also solves bug
> - [x] Fastly changing forms a few times, somwhen runs into an error, that overwrites one form with another one, and logs TypeError: "this.form.form is undefined" on console

### CODE REVIEW

**Comment by jancborchardt** [comment]
This needs Vue reviewers :) @skjnldsv @juliushaertl @ChristophWurst

**Comment by juliushaertl** [comment]
I'm not a big fan on having the whole fetch logic inside of the component itself, having state management and just obtaining the form from there would be a bit cleaner imo, but I have no idea about the form code so @skjnldsv can probably judge better than me. :wink:

**Comment by jotoeri** [comment]
@ma12-co Added you for review, as you wrote the cancelable request?! Is this proper usage here?

@juliushaertl In fact @skjnldsv newly wrote this fetch logic here, so i can't tell you why he did. But we load the different forms on changes of the vue-router and can change their data. So php (&state-management?) is not involved in between. Would mean we would need to provide all possible data in state-management, and when writing changes to db, the states needed to be adapted each time...?!

**Comment by jotoeri** [comment]
Nice. Thank you both for reviewing! :)

**Comment by skjnldsv** [comment]
> I'm not a big fan on having the whole fetch logic inside of the component itself, having state management and just obtaining the form from there would be a bit cleaner imo, but I have no idea about the form code so @skjnldsv can probably judge better than me.

Yeah, no need for a full state here as we only keep a stupid array oj objects.
I thought it would clearly be overpowered to have a full vuex app framework implemented.

I guess we can still split things into services later on as cleanups :)

**Pull request merged**
