### PR TITLE
Code reformat and small fixes. 

### PR DESCRIPTION
**Pull request by JanDragon**
Signed-off-by: Jan-Laurin Frey <janlaurinfrey@gmail.com>

Will work in future more active on this app. :)

### CODE REVIEW

**Comment by skjnldsv** [comment]
Wow, this is quite some work to review :grin:

**Comment by skjnldsv** [comment]
@JanDragon can you optimise the svgs with our svg tool please?
https://github.com/nextcloud/server/blob/master/build/image-optimization.sh

**Comment by JanDragon** [comment]
> @JanDragon can you optimise the svgs with our svg tool please?
> https://github.com/nextcloud/server/blob/b6a9cf21a302dd9e07e72ff12e927ff98b12f893/build/image-optimization.sh#L10

Yep done :)

**Comment by rullzer** [comment]
Sees the linting is not to happy with this...

**Comment by rullzer** [comment]
@JanDragon can you run: npm run lint and see what needs fixing?

**Comment by skjnldsv** [comment]
Obsolete after #208

**Pull request closed without merging**
