### PR TITLE
Add support of multi-columns descriptions

### PR DESCRIPTION
**Pull request by Koc**
Now we can use multi-columns descriptions thankful to [markdown-it-container](https://github.com/markdown-it/markdown-it-container) plugin

```markdown
::::: columns
:::: column-double
first column has double relative width (ie 2/3 of total width) 
::::
:::: column-single
second column has single relative width (ie 1/3 of total width)
::::
:::::
```

<details>
  <summary>:mag:  Preview</summary>

  image
  image
</details>

### CODE REVIEW

**Comment by susnux** [comment]
I am not sure about this, I do not see a good use case and will make thing more complex.
I would probably stick with CommonMark to keep it simple.

Opinions @jancborchardt @Chartman123 ?

**Comment by Chartman123** [comment]
Yeah same for me... another dependency for only a really small benefit.

**Comment by Koc** [comment]
for our use case It has sense for students quizzes, e.g. we have some image/schema on the left column and a question on the right column

**Comment by Koc** [comment]
Updates:
- properly handle columns on mobile
- added more real-life example in PR description
- fixed pipeline

**Comment by Chartman123** [comment]
@Koc thanks for the updated description with the preview... How would this work together with your other PR to implement Text as a Markdown editor? As far as I could see Text doesn't support multi-columns.

**Comment by Koc** [comment]
@Chartman123 I've plan to close #2164 because it requires much more work than I expected for adding images support. So there are no any conflicts with this 2 PRs anymore :smiley:

**Review by jancborchardt — COMMENTED** [review]
If Text doesn’t support multi-columns, I am also hesitant to add this. As mentioned, we shouldn’t stray too much from a standard, and at least be internally consistent.

**Comment by Chartman123** [comment]
@Koc you can follow the blocklist link in the last post to add your username to the list so that your PRs don't get this feedback post :)

**Pull request closed without merging**
